//Liste des citations
module.exports = {

    //"Citation": "Auteur"
    "Va voir à l'ehpad, le sexe est sale quand la toilette est mal faite ... c'est à dire tous les jours": "Xoxtin",
    "elle a le palais détruit, go l'amener rue d'arshot elle est plus bonne qu'a avaler des bites": "Xoxtin",
    "y'a jamais de mauvais moment pour sortir sa bite": "Xoxtin",
    "C'est important pour pouvoir taper dans le fond d'en avoir une bien dure": "Xoxtin",
    "Tu attrapes la queue, tu glisses les boules dans ta bouche, et tu tires délicatement pour les décoller de la queue": "Xoxtin",
    "VIVE LA CLEAVE": "Tout le monde",
    "Tu prends alots et bbk et boom boom": "Darksoul",
    "jattend la maj pour up ma bbk 7 etoile": "Darksoul",
    "ta essayer lots bbk vs ca ?": "Darksoul",
    "gros higt kik sans sa gueule alors\nmais ya que moi qui pe la frapper si elle est pas sage\nc en forgeant quon devien forgeron tfacon": "Darksoul",
    "T1: alots 314, T2: ran 315": "Hans",
    "J'ai besoin d'amour et comme j'ai pas de meuf sg me donne des ml pour me consoler": "Daarky",
    "Sg bande de sombre pute si vous me donnez pas des ml 5 je vais venir toquer a votre porte er vous brisé les genoux bande de catin de mes deux": "Daarky",
    "Crois en la cleave et la cleave te le rendra": "Daarky",
    "Toute la famille de sg va finir au goulag en 1v1 contre moi\nJe vais les exterminer c petite salope": "Daarky",
    "Le seul truc qui sera cité ça sera le nom de la personne qui m'a ping qui va finir dans un coffre de voiture direction Paname si je le chope": "Daarky",
    "Je peux pas rester dans cette guilde en faite\nJe vais break mental a force de voir des whales pareils full lucksack": "Daarky",
    "Putain j'ai fait 50€ de course pour pas grand chose\nAberrant les prix\nJe vais continuer de faire le ramadan et manger que 1 fois tout les 2j beaucoup plus rentable mdr": "Daarky",
    "Le jour où j'aurais arby les Charles je vais leur chier a la gueule avec le elbris de fdp il vas counter et arby va revenir et violer ces parents": "Daarky",
    "Qui joue avec le son aussi\nDès qu'une waifu se fait hit ta l'impression elle se fait violer\nJ'ai try une fois plus jamais je recommence": "Daarky",
    "Vasie ce tel de merde qui envoie des stickers tout seul mtn\nVivement que j'ai un pc que je le fracasse par terre": "Daarky",
    "Je viens d'apprendre à volé\nC'est terrible\nJe roule en trotinette sur un trottoir j'allume pas la lumière parceque ya des voitures en face donc chui pas fdp\nY avait un rebord de fdp genre 10cm au bout du trottoir je l'ai pas vue\nJ'ai volé sur 2m\nJe me suis éclaté ça mère": "Daarky",
    "- Mange alors\n- Pas les moyens": "Xoxtin & Daarky",
    "Utilisation simple et sans bavure de la méthode": "Soow",
    "Elle avait un cul qui ne se refuse pas": "EFX",
    "je lui explose son fion jusqu'à ce qu'elle soit incontinente et elle en tombera amoureuse de moi": "EFX",
    "Bruh je t'assure que si je pouvais l'avoir à portée de chibre elle marcherait en canard avec un air hagard": "EFX",
    "Dans cet appel à se faire bully on peut entrevoir la raison qui pousse les gens au bdsm ou la recherche de l'affection à n'importe quel prix": "EFX",
    "Nous sommes tous le degen de quelqu'un": "EFX",
    "T'as une bite, tu te branles mais ça ne fait pas de toi quelqu'un de sexuellement actif": "EFX",
    "VIVE LA SPEED": "Bistouflee",
    "CHAVAIS CHAVAIS": "Bistouflee",
    "https://www.youtube.com/watch?v=r-35MoyCfM0": "Bistouflee",
    "C'était fort sur les perso comme carrot/atywin & co où t'avais vraiment envie que ces persos soient dans le mal vu que les compos étaient très différentes, là normalement une hwa c'est ce qu'on peut appeler \"une ancre\" qui te permet de te reposer dessus si jamais tu veux pivoter sur plusieurs styles de jeu (Aria, Aravi et accessoirement Sylvian sont des ancres). C'est juste là pour te rappeler que tu peux pas stall, et que tu dois draft pour counter cette ancre particulière, et si tu le fais, bah le mec en face pivote pour te counter tes picks si possible (vu que tous le monde à pas tous les persos de gear).": "Fhulgrim",
    "J'espère qu'un jour le mec qui a créer clilias\ncrève d'un cancer de l'intestin\nen voyant sa soeur se faire violer par un coréen du nord\nje le souhaite de tout mon coeur": "Fhulgrim",
    "Tout arrive plus vite à qui court après": "Punch",
    "Tu perds pas car il meilleur que toi mais car t'es un 1head , même si tu chill contre du top200 là t'aurais perdu car c'est juste ton cerveau le problème": "Punch",
    "Daarky c'est le gamin indigne qui fait des caprices et hurle jusqu'à plus voix dans les magasins , il se roule parterre et tout pour avoir un jouet , un vrai monstre je suis père je pète un câble": "Punch",
    "J'ai volé des cartes Yu-Gi-Oh moi pendant une recrée , une vrai merde (moi) le mec chialait car il avait full carte rare et moi sans état d'âme je faisais le mec désolé pour lui alors que j'avais toute ses cartes dans mon sac": "Punch",
    "Il faut bien sympathiser avec le diable quand on combat les flammes": "Monstur",
    "ah non moi j'ai autant de charisme que ervalen": "Celaloose",
    "Jvai roulez un joint de la taille de ma bite pour te fumer les entrailles": "Seji",
    "Perso je cleave avec DC": "Seji",
    "Salut tu te rapelle de moi, tu me dois de la thune": "Zickys",
    "Mange ma canne": "Zickys",
    "formula adin\nkalashnikov dra dra\nwe're going to moscow": "Zickys",
    "Pendant les scènes de sex je regarde les commentaires en attendant la suite du scénario": "D4",
    "Uwu guys i missed the \"chaussette sales\" from vivian, did someone know where they are ?\nOwO\nBAKA BAKA BAKA BAKA DE PEEPO DE PERFO": "Rossi",
    "Mon ADN supérieur ma permis de voir en soow un bon leader (chef/meneur/dirigeant)  supreme et donc nous pouvons en déduire que soow est le meilleur": "Rossi",
    "Je men vais taper une queue de l'enfer pour faire sortir les larmes de ma bite": "DeadNobody",
    "Les herbivores vous foutez quoi sur discord allez dans les prés brouter": "Gofri",
    "de trop gros branleurs vous me tirez vers le bas": "Gofri",
    "Crois en moi qui crois en toi": "Elakir",
    "As-tu une dernière volonté à accorder au roi des sables ?": "Elakir",
    "Deviens bon": "Astérie",
    "MISSION COMPLETE": "Reroll",
    "J'avais envie de casser la gueule a un arabe ça tombe bien": "Liddoch",
    "@darksoul j'ai un probleme quand je s2 avec alots il silence les ennemis au lieu de push je comprends pas": "Doudi",
    "Chin and Gandji\nChand choug chénouu\nKitchen in a dongeon\nI swear to god to bang cow\nFuuu wana touching you\nMy mama wasn't love me\nI swear to god to bang cow": "Lainien",
    "En meme temps je suis family friendly geared": "Perfo",
    "AH c'est mieux la j'entend ta belle voix parfaitement a deux doigts de soulever mon bureau": "Disgrace",
}